// import { Inter } from "next/font/google";
import "./globals.css";

// const interFont = Inter({
//   variable: "--font-inter",
// });



export const metadata = {
  title: "IPhone 15 Pro",
  icons: {
    icon: "/assets/images/apple.svg",
    shortcut: "/assets/images/apple.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
